/**
 * Verify the demo EMVCo payload generated by apps/web/lib/qr/demo-qr.ts
 * decodes cleanly with the real @mova/qr decoder (CRC-valid, correct fields).
 */
import { decodeEmvco, crc16Ccitt, stringToUtf8 } from "@mova/qr";
import { DEMO_EMVCO_PAYLOAD, DEMO_QR_SUMMARY } from "../apps/web/lib/qr/demo-qr.js";

const d = decodeEmvco(DEMO_EMVCO_PAYLOAD);

console.log("payload       :", DEMO_EMVCO_PAYLOAD);
console.log("summary       :", DEMO_QR_SUMMARY);
console.log("crcValid      :", d.crcValid);
console.log("parseErrors   :", d.parseErrors.length);
console.log("merchant      :", d.merchantName, "|", d.merchantAccount);
console.log("amount        :", d.amountRaw, "| currency", d.currencyCode);
console.log("city          :", d.merchantCity);
console.log("country       :", d.countryCode);
console.log("category      :", d.categoryCode);

if (!d.crcValid) {
  console.error("FAIL: CRC invalid — demo payload would be blocked fail-closed.");
  process.exit(1);
}
if (d.parseErrors.length > 0) {
  console.error("FAIL: parse errors", d.parseErrors);
  process.exit(1);
}
if (d.merchantName !== "MOVA TEST MERCHANT" || d.amountRaw !== "200.00" || d.currencyCode !== "458") {
  console.error("FAIL: unexpected field values");
  process.exit(1);
}
// Independent CRC re-check over the TLV body (exclude the "6304" tag + 2-char
// length + 4-char value = 8 chars).
const crc = crc16Ccitt(stringToUtf8(DEMO_EMVCO_PAYLOAD.slice(0, -8))).toString(16).toUpperCase().padStart(4, "0");
if (!DEMO_EMVCO_PAYLOAD.endsWith(crc)) {
  console.error(`FAIL: embedded CRC ${DEMO_EMVCO_PAYLOAD.slice(-4)} != computed ${crc}`);
  process.exit(1);
}
console.log("OK — demo QR payload is valid and decodes cleanly.");
